import * as React from "react";
import Box from '@mui/material/Box';
import TopBar from "@/components/TopBar";
import LeftSidebar from "@/components/LeftSidebar";
import ThemeRegistry from "@/theme/Themeregistry";
import NextAuthSessionProvider from "@/app/providers/sessionProvider";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <ThemeRegistry session={session}>
      <body>
      <NextAuthSessionProvider>
          <Box sx={{ display: 'flex' }}>
              <TopBar/>
              <LeftSidebar/>
              {children}
          </Box>
      </NextAuthSessionProvider>
      </body>
      </ThemeRegistry>
    </html>
  )
}
