"use client"
import {SessionProvider} from "next-auth/react";
import {Providers} from "./providers";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body>
      <SessionProvider session={session}>
          <Providers>
          {/*<AppBar/>*/}
        {children}
          </Providers>
      </SessionProvider>
      </body>
    </html>
  )
}
